name: Release

on:
  push:
    tags:
      - "v*.*.*"
  # Allow manually trigger.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - Could use: dtolnay/rust-toolchain@stable
      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

      - name: Set up MacOS Cross Compiler
        uses: Timmmm/setup-osxcross@v2
        with:
          osx-version: "12.3"

      - name: Install Rust target
        run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu x86_64-apple-darwin aarch64-apple-darwin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu --target x86_64-apple-darwin --target aarch64-apple-darwin

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            target
